### ISSUE TITLE
Can't you do a better job than this on title?

### ISSUE THREAD

**Issue by jbrucker** [ThanadolU/ku-international-cafe#14]
https://github.com/ThanadolU/ku-international-cafe/blob/c43748d3d9447deb8477b7e7fd764d71dd382e56/README.md?plain=1#L1

**Comment by thanidacwn** [comment]
Already fixed it, thank you.
<img width="846" alt="Screenshot 2566-08-22 at 15 20 42" src="https://github.com/ThanadolU/ku-international-cafe/assets/92778351/84bbe368-b586-459f-8af3-733b532a03a2">
