### ISSUE TITLE
Thai Food does not have "Assignee"

### ISSUE THREAD

**Issue by jbrucker** [ThanadolU/ku-international-cafe#15]
You should add your name to a task when you take or are assigned a task.

**Comment by thanidacwn** [comment]
Thank you, I'm already added it.
<img width="336" alt="Screenshot 2566-08-22 at 15 06 19" src="https://github.com/ThanadolU/ku-international-cafe/assets/92778351/1eb0b172-00ad-4fec-9973-f040f8c4031e">
